### ISSUE TITLE
Add links to published paper and Zenodo package

### ISSUE THREAD

**Issue by korenmiklos** [REStud/annotated-READMEs#7]

**Comment by korenmiklos** [comment]
For existing READMEs, at the top, add markdown links to published paper (with DOI) and Zenodo (with DOI).
```
[Published article](https://doi.org/... or restud.com)

[Replication package](https://doi.org/...)
```

**Comment by csokaimola** [comment]
@korenmiklos 26460.md already had the links, should others also be formatted like that?

`title: "Replication Package for: Should Robots be Taxed?"`
`authors: Joao Guerreiro, Sergio Rebelo, Pedro Teles`
`package_doi: http://doi.org/10.5281/zenodo.4568354`
`article_doi: https://doi.org/10.1093/restud/rdab019`
